### ISSUE TITLE
Get first day of week for Locale

### ISSUE THREAD

**Issue by alamothe** [js-joda/js-joda-locale#123]
How do we get first day of week for a given Locale?

E.g. for some locales it is SUNDAY, while for most it is MONDAY.

Thanks!

**Comment by phueper** [comment]
Hi,

thanks for using js-joda-locale!

You could get an instance of `WeekFields` using `WeekFields.of(Locale)` ... and then use the `.firstDayOfWeek()` function...  which will return a `DayOfWeek` instance

Hope this helps? I will close this issue, feel free to reopen if you have further questions

Regards, Pattrick
