### ISSUE TITLE
Think about nicer ways to deliver prebuilt locales and require them

### ISSUE THREAD

**Issue by phueper** [js-joda/js-joda-locale#40]
e.g. something like moment does (require('js-joda-locale/de')) ...

**Comment by dcosson** [comment]
Agree, I'm glad this library is finally out but installing this is insane just to be able to display times with am/pm.  I tried to follow the webpack steps but it's not clear which steps from the other sections of the doc I still need to follow first to get it working. I'm getting an error `cannot find module "fs"` in the webpack build process. Gonna give up for now and just convert them to basic date's or something and format with a simpler library.

Is it possible to just install the "core" or "full" bundles of cldr data using npm without any more complex configuration, and then rely on tree-shaking by only importing the locales you actually need with something like `import jsJodaLocal from 'js-joda-locale/build/package/en'` with a separate line for every language?

If so that would greatly simplify the docs to describe that first.

**Comment by phueper** [comment]
I agree... i especially agree that my documentation skills are somewhat lacking... i think the current description is way to complicated and it is actually not *that* complicated... i will try to come up with a better explanation what needs to be done...

**Comment by phueper** [comment]
Sorry, I didn't have time yet to look into this further.. I hope to have some time during Christmas break

**Comment by simonfox** [comment]
Agree! Loving `js-joda` but this is one is a little painful for me. I'm on Windows so banging into #41 which compounds the problem. I need this package for day and month names, but in the meantime have rolled my own extensions.

**Comment by phueper** [comment]
Sorry.. not much time lately :( Just out of curiosity @dcosson @simonfox ... which prebuilt locales would you expect to see? `en` is pretty obvious, i guess.  Would you also expect country specific locales ? `en_US`, `en_GB`? other languages? (`es`, `de`, `fr`, `cn`, ...?)

**Comment by simonfox** [comment]
My requirements are just to be able to get day of week names and month names so `en` would cover it.

Do you have some ideas on how this might look? I could possibly help out...

**Comment by UltraMarco** [comment]
Please, don't forget "it" if you're working on prebuilt locales... ;)

**Comment by phueper** [comment]
the problem for me here is package size... if i create a prebuilt bundle with all `en*` locales i get a (minified) file that is 3.7M in size... `en-US` only results in 152K ... for `de*` (392K) vs `de-DE` (152K)  it is slightly better (same goes for `it.. `es` and `fr` have quite large packages as well if not targetted for a single country)


this will greatly increase the size of the npm package if we include many of these... and a ~4M `en` file is not really useful i would guess ... 

i don't know how to solve this yet, maybe we need to switch to some kind of multi-module setup where we automatically create `js-joda-locale_<locale>` packages ? hmmm

**Comment by phueper** [comment]
fwiw ... some work on building prebuilt locales: https://github.com/phueper/js-joda-locale/tree/prebuilt_locales

**Comment by phueper** [comment]
if anybody is willing to test this... i'd be happy to get some feedback... 
if you
`npm i -S js-joda-locale@phueper/js-joda-locale#prebuilt_locales`

you should be able to 
```
var joda = require('js-joda').use(require('js-joda-timezone'));
joda.use(require('js-joda-locale/dist/prebuilt/minified/en'))
```
or
```
var joda = require('js-joda').use(require('js-joda-timezone'));
joda.use(require('js-joda-locale/dist/prebuilt/en'))
```

and then format with the specified locale... i currently pushed the following locale packages:

- de
- de-DE
- en
- en-US
- es
- fr
- hi
- it
- it-IT
- zh
(the ones without a country suffix are for all countries in that locale, so `en` should be able to format `en-CA`, `en-GB`, `en-US`, ...
These are in no way final, just what i currently came up with and was playing around with...

**Comment by simonfox** [comment]
@phueper awesome! this works for me....(also I'm on Windows, and using `yarn`). 

setup a little wonky with Typescript, but otherwise :+1:
```
import { use as jsJodaUse } from 'js-joda';
import * as jsJodaTimezone from 'js-joda-timezone';
import * as jsJodaLocale from 'js-joda-locale';

jsJodaUse((jsJodaTimezone) as any).use(jsJodaLocale);
```

**Comment by phueper** [comment]
Hi @simonfox ... thanks for testing!

However, from the snippet you posted it looks like you didn't use the prebuilt package, but the "plain" js-joda-locale package (that would be loading locale data directly from cldr-data) ... could you try replacing 

```
import * as jsJodaLocale from 'js-joda-locale';
```
with
```
import * as jsJodaLocale from 'js-joda-locale/dist/prebuilt/en';
```

Cheers, Pattrick
Oh, and yes, the typescript seems a little strange... i'm not a typescript user myself, but we could think about providing a `.ts` definitions file for `js-joda-locale` and `js-joda-timezone` as well...

**Comment by simonfox** [comment]
Sorry for confusion @phueper ....I just configured my bundler to bundle prebuilts as `'js-joda-locale'`, pointed that at `en` and then `en-US` prebuilts and both worked fine (`en-US` much more usable size).

**Comment by phueper** [comment]
@simonfox  ah... ok... great! thx :)

**Comment by UltraMarco** [comment]
Sorry for late reply and congratulations for this library, it fills many gaps in js date management.
I tested sample code too and it/it-IT packages are correctly imported, but if I try this in my TypeScrypt (Angular) test:

`import { use as jsJodaUse, LocalDate } from 'js-joda';
import * as jsJodaTimezone from 'js-joda-timezone';
import * as jsJodaLocale from 'js-joda-locale/dist/prebuilt/it-IT';

jsJodaUse((jsJodaTimezone) as any).use(jsJodaLocale);
console.log(LocalDate.parse('1 aprile 2018'));`

the last line gives a DateTimeParsingException:
"Text '1 aprile 2018' could not be parsed at index 0: 1 aprile 2018, at index: 0" 

Why doesn't "parse" use the IT locale? Probably I'm missing something obvious.

BTW, it would be very useful to have a simple DateAdapter module for [DatePicker](https://material.angular.io/components/datepicker/overview) component of Angular Material, as LocalDate would be perfect for this use case, even more suitable than Moment implementation. Unfortunately I'm bit of an autodidact and I'm not able, but I think it would be easy for a skilled one.

**Comment by phueper** [comment]
Hi @UltraMarco  ... thanks for testing, and thanks for your reply

first of all, `LocalDate.parse()` without a specified formatter will only parse an ISO date, like:

`LocalDate.parse('2018-04-01')` ... see 
https://js-joda.github.io/js-joda/esdoc/class/src/LocalDate.js~LocalDate.html#static-method-parse

i'm not much of a typescript user, but i managed to get your example to work in plain JS/Node:

```
const joda = require('js-joda').use(require('js-joda-timezone')).use(require('../build/prebuilt/it'))

const {LocalDate, DateTimeFormatter, Locale} = joda

console.log(LocalDate.parse('1 aprile 2018', DateTimeFormatter.ofPattern('d MMMM yyyy').withLocale(new Locale('it'))));
```

so, you need to specify the Formatter for the pattern you are trying to parse as well as the locale, i think this is a little complicated and not very intuitive, but it works

Note, that i found out, that cldr-data doesn't seem to contain specific `it-IT` locale data, so you will have to use the `it` locale and prebuilt package

I am working on releasing the prebuilt packages as separate `js-joda-locale_<locale>` packages to npm, but am not quite done with that yet.

As to your question regarding the Angular DatePicker.. i agree, that LocalDate would very much be suited for that. This is in my oppinion a big advantage of js-joda/JSR-310 over moment and other date libraries, that we have domain specific types like `LocalDate` ... that explicitly do not have a time component if you don't need one... 
That said, it is not something that we will provide here, we are focussing solely on the js-joda libraries. we are happy to provide help for users of it, but providing an angular library/plugin would need to be done outside of this module :)

Cheers, Pattrick

**Comment by phueper** [comment]
finally... locale specific packages have been release (new namespace `@js-joda/locale*`

so ... this can be closed

**Comment by kuhnroyal** [comment]
Can I somehow register 2 rebuilt locales without needing the `@js-joda/locale` package

**Comment by phueper** [comment]
Hi @kuhnroyal  ,

sadly, that is currently not possible until #93 is resolved :( ... currently the last loaded prebuilt locale definition that was loaded/required "wins" 

Regards, Pattrick

**Comment by kuhnroyal** [comment]
Thanks @phueper, watching that issue
