### ISSUE TITLE
download link to prebuilt packages

### ISSUE THREAD

**Issue by henryw374** [js-joda/js-joda-locale#78]
Hi,

I'm trying to work out the download link for the prebuilt packages. For example https://github.com/js-joda/js-joda-locale/archive/v1.1.0.zip is the link to the main archive, but what about the prebuilts? Sorry I have tried a few things but not working.

Thanks

**Comment by phueper** [comment]
Hi,

thanks for reporting... i am having trouble uploading the locale specific packages (npm complains about the package names and doesn't let me upload... i have written with npm support several times but couldn't find a solution yet (actually haven't got an answer in a few weeks))

Which locale would you like to have? I will try to get this somehow working... if npm doesn't help me i might try some different naming scheme

Regards, Pattrick

**Comment by henryw374** [comment]
Hi Pattrick, en-US would be fine for me. I just need DateTimeFormatter to print out "dd MMM yyyy hh:mm", so pretty basic stuff.

For now I am directly downloading the pre-built package: https://raw.githubusercontent.com/js-joda/js-joda-locale/8e384141cb191c8cbf35b2844cab15ace035f806/packages/en-us/dist/index.js

Thanks

**Comment by phueper** [comment]
Hi,

sorry for my late reply... i still haven't heard from npm. so i think i will have to figure this out by myself somehow and come up with a workaround :/ 

Anyway... for en-US you could use this npm package: https://www.npmjs.com/package/js-joda-locale_en

it includes all `en-*` locales ... the idea is to also have a en-US specific package, but that isn't allowed by npm for some reason currently :/

I hope this helps?

Cheers, Pattrick

**Comment by henryw374** [comment]
Hi Pattrick, no problem. I did try to use the js-joda-locale_en package, but all that's in it is a package.json. in that, there is `index: dist/index.js` , but i don't understand where it is supposed to come from. After installing and bringing up node repl, both `require('js-joda-locale')` and `require('js-joda-locale_en')` fail. 

Something else a bit strange, when I tried to see what versions are available, it doesn't show me anything: `npm show js-joda-locale_en@* version`

Any ideas? 

Thanks,
Henry

**Comment by phueper** [comment]
Hi,

oh ... oops.. i didn't realize that the file is missing :see_no_evil: ... will check that...

as to the `npm show` ... i don't know, maybe it is because the versions are including the `-pre` and are tagged `beta` ... not sure though... `npm show js-joda-locale_en`  does show some info  :thinking: 

Regards, Pattrick

**Comment by phueper** [comment]
Hi again,

i think i fixed the problem with missing file... https://registry.npmjs.org/js-joda-locale_en/-/js-joda-locale_en-1.1.0-pre5.tgz  ... should contain package.json and the dist/index.js ... i would be interested if this works for you

This is still `tag`ged as `beta` since the naming issue with the country specific packages , e.g. `js-joda-locale_en-us` still exists :/ ... npm reports detecting a "spam issue" with these names... for reasons i don't quite understand :(

Regards, Pattrick

**Comment by henryw374** [comment]
Hi, I just tried again with npm, but it downloads https://registry.npmjs.org/js-joda-locale_en/-/js-joda-locale_en-1.1.0-pre.tgz, not https://registry.npmjs.org/js-joda-locale_en/-/js-joda-locale_en-1.1.0-pre5.tgz   - (missing  '5' at the end there). and the one without the 5 doesnt contain the dist. 

And I know this is a separate issue, but at almost 1MB zipped it's really too big for me to use. I do have a workaround of downloading the en_us pre-package straight from github, so this isn't blocking me.

**Comment by phueper** [comment]
ok... i released new versions of these packages ... i workarounded the name issue... the packages are now called `@js-joda/locale*` ... and the old name packages are deprecated... now also a `@js-joda/locale_en-us` package is available ... i'd be glad to get feedback if it works 
Note however, that the usage has slightly changed, no need to `.use` the plugin on `js-joda` anymore ...  see the examples 

i'll close this issue now, feel free to reopen or report a new issue if you continue to have problems

**Comment by henryw374** [comment]
all looks good thanks

https://github.com/js-joda/js-joda-examples/blob/master/examples/node/node-modules-07.js
